config/routes.rb
Rails.application.routes.draw do
  get 'books/index'
  resources :books
  root :to => redirect('/books')

  get '/books/:id/similar_books' => 'books#search_similar_books',
    as: :search_similar_books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  def self.all_genres
    [
      'Science fiction',
      'Drama',
      'Action and Adventure',
      'Romance',
      'Mystery',
      'Horror'
    ]
  end
  validates :title, :presence => true
  validates :publish_date, :presence => true
  validate :published_1967_or_later # uses custom validator below
  validates :genre, :inclusion => {:in => Book.all_genres}
  def published_1967_or_later
    errors.add(:isbn, 'must be added if the book was published after 1967') if
    publish_date > Date.parse('1 Jan 1967') && (isbn.nil? || isbn.empty?)
  end
  before_save do
    self.title = title.split.map(&:capitalize).join(' ')
  end
  def self.similar_books(book)
    Book.where author: book.author
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # index page
  def index
    if !params.key?(:genres)
      params[:genres] = {}
    end
    permitted = params.permit(:sort, genres: params[:genres].keys)
    sort = permitted[:sort] || session[:sort]

    case sort
    when 'title'
      ordering, @title_header = {:title => :asc}, 'hilite'
      @date_header = nil
    when 'publish_date'
      ordering, @date_header = {:publish_date => :asc}, 'hilite'
      @title_header = nil
    end

    @all_genres = Book.all_genres
    @selected_genres = permitted[:genres] || session[:genres] ||  {}
    if @selected_genres == {}
      @selected_genres = Hash[@all_genres.map {|genre| [genre, genre]}]
    end

    if permitted[:sort] != session[:sort] or permitted[:genres] != session[:genres]
      session[:sort] = sort
      session[:genres] = @selected_genres
      redirect_to :sort => sort, :genres => @selected_genres and return
    end

    @books = Book.where(genre: @selected_genres.keys).order(ordering)
  end

  # detail page
  def show
    id = params[:id] # retrieve book id from routed
    @book = Book.find(id) # look it up
  end

  # new book page
  def new
    @book = Book.new
  end

  def create
    params.require(:book)
    permitted = params[:book].permit(:title, :isbn, :author, :genre, :description, :publish_date)
    @book = Book.new(permitted)
    if @book.save
      flash[:notice] = "#{@book.title} was successfully created."
      redirect_to books_path
    else
      render 'new'
    end
  end

  # edit existing book
  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    params.require(:book)
    permitted = params[:book].permit(:title, :isbn, :author, :genre, :description, :publish_date)
    if @book.update(permitted)
      flash[:notice] = "#{@book.title} was successfully updated."
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  # delete book
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book '#{@book.title}' deleted."
    redirect_to books_path
  end

  # similar books - same author
  def search_similar_books
    @book = Book.find(params[:id])
    if @book.author.nil? || @book.author.empty?
      flash[:warning] = "'#{@book.title}' has no author info"
      redirect_to books_path
    else
      @books = Book.similar_books(@book)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book_form.haml
= label :book, :title, 'Title'
= text_field :book, :title
%br 
%br 

= label :book, :author, 'Author'
= text_field :book, :author
%br
%br 

= label :book, :isbn, 'ISBN'
= text_field :book, :isbn
%br
%br 

= label :book, :genre, 'Genre'
= select :book, :genre, ["Science fiction", "Drama", "Action and Adventure", "Romance", "Mystery", "Horror"]
%br
%br 

= label :book, :description, 'Description'
= text_area :book, :description
%br
%br 

= label :book, :publish_date, 'Published on'
= date_select :book, :publish_date, start_year:1900

%br

app/views/books/_table_rows.haml
%thead
  %tr
    %th{:class => @title_header}= link_to 'Book Title', books_path(:sort => 'title', :genres => @selected_genres), :id => 'title_header'
    %th Genre
    %th Author
    %th ISBN Number      
    %th{:class => @date_header}= link_to 'Publish Date', books_path(:sort => 'publish_date', :genres => @selected_genre), :id => 'publish_date_header'
    %th More info
%tbody
  - @books.each do |book|
    %tr
      %td= book.title 
      %td= book.genre 
      %td= book.author
      %td= book.isbn
      %td= book.publish_date.strftime("%B %d, %Y")
      %td= link_to "More about #{book.title}", book_path(book)

app/views/books/edit.html.haml
%h2 Edit Book

= form_tag book_path(@book), :method => :put do
  - unless @book.errors.empty?
    #warning
      Errors prevented this book from being #{controller.action_name}d:
      %ul
        - @book.errors.full_messages.each do |error|
          %li= error
  = render :partial => 'book_form'
  %br
  = submit_tag 'Update Book Info'

app/views/books/index.html.haml
%h1 All Books
= form_tag books_path, :method => :get, :id => 'genres_form' do
  = hidden_field_tag "title_sort", true if @title_header
  = hidden_field_tag ":publish_date_sort", true if @date_header
  Include:
  - @all_genres.each do |genre|
    = genre
    = check_box_tag "genres[#{genre}]", 1, @selected_genres.include?(genre), :id => "genres_#{genre}"
  = submit_tag 'Refresh', :id => 'genres_submit'
%table#books
  = render :partial => 'table_rows'
  = link_to 'Add new book', new_book_path

app/views/books/new.html.haml
%h2 Create New Book

= form_tag '/books', :method => :post do

  - unless @book.errors.empty?
    #warning
      Errors prevented this book from being #{controller.action_name}d:
      %ul
        - @book.errors.full_messages.each do |error|
          %li= error

  = render :partial => 'book_form'
  %br
  = submit_tag 'Save Changes'

app/views/books/search_similar_books.html.haml
%h1 Similar books to #{@book.title}

%table#similar_books
  %thead
    %tr
      %th Book Title
      %th Genre
      %th Author
      %th ISBN Number   
      %th Publish Date       
      %th More Info
  %tbody
    - @books.each do |book|
      %tr
        %td= book.title 
        %td= book.genre
        %td= book.author
        %td= book.isbn
        %td= book.publish_date
        %td= link_to "More about #{book.title}", book_path(book)

app/views/books/show.html.haml
-# in app/views/books/detail.html.haml
%h2 Details about #{@book.title}

%ul#details
  %li
    Genre:
    = @book.genre
  %li
    Author:
    = @book.author
  %li
    ISBN number:
    = @book.isbn
  %li
    Publish date:
    = @book.publish_date.strftime("%B %d, %Y")


%h3 Description:

%p#description= @book.description

= link_to 'Edit info', edit_book_path(@book)
= link_to 'Find Books With Same Author', search_similar_books_url(id: @book.id)
= link_to 'Delete', book_path(@book), :method => :delete
= link_to 'Back to book list', books_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title My favourite books!
    = stylesheet_link_tag 'application'
    = javascript_pack_tag 'application'
    = csrf_meta_tags

  %body
    #main
      = yield
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]